# Generated by Django 4.0.4 on 2022-05-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catprofile', '0002_catprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='catprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
