# Generated by Django 4.0.4 on 2022-05-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catprofile', '0005_signup_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
