# Generated by Django 4.0.4 on 2022-05-04 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('meow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='food.meow')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
